#
# Sysbuild: nRF7002 WiFi firmware (full) + BLE controller on netcore (hci_ipc)
#

SB_CONFIG_WIFI_NRF70=y

# nRF5340 ma osobny netcore — buduj na nim controller BLE (hci_ipc),
# żeby cpuapp mógł rozmawiać po IPC z hostem BT.
SB_CONFIG_NETCORE_HCI_IPC=y
